services:
  api:
    build: .
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      DB_SOURCE: postgresql://postgres:secret@db:5432/simple_bank?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple_bank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d simple_bank"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s